apiVersion: v1
kind: Pod
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  containers:
  - name: gitlab
    image: gitlab/gitlab-ce:latest
    ports:
    - containerPort: 80
      name: http
    env:
    - name: GITLAB_OMNIBUS_CONFIG
      value: |
        external_url 'http://gitlab.k3d.gitlab.com'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['initial_root_password'] = 'GitLabP@ssw0rd2026'
    livenessProbe:
      httpGet:
        path: /-/health
        port: 80
      initialDelaySeconds: 120
      periodSeconds: 10
    resources:
      limits:
        memory: 2Gi
        cpu: 1
      requests:
        memory: 1Gi
        cpu: 500m
    volumeMounts:
    - name: gitlab-data
      mountPath: /var/opt/gitlab
  volumes:
  - name: gitlab-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gitlab
