apiVersion: v1
kind: Pod
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  containers:
  - name: gitlab
    image: gitlab/gitlab-ce:latest
    ports:
    - containerPort: 80
      name: http
    env:
    - name: GITLAB_OMNIBUS_CONFIG
      value: |
        external_url 'http://gitlab.k3d.gitlab.com'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['initial_root_password'] = 'fpalumbo42'
    resources:
      limits:
        memory: 8Gi
        cpu: 4
      requests:
        memory: 6Gi
        cpu: 3
    volumeMounts:
    - name: gitlab-data
      mountPath: /var/opt/gitlab
  volumes:
  - name: gitlab-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  selector:
    app: gitlab
