Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "fpalumboS" do |server|
    server.vm.hostname = "fpalumboS"

    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "fpalumboS"
      vb.memory = 1024
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/install_k3s.sh"
  end
end
